Django_User_Authentication/user-profile-with-django-master/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/change_password/<str:username>', views.change_password, name='change_password'),
    path('profile/edit/<str:username>', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>', views.view_profile, name='profile'),
]

Django_User_Authentication/user-profile-with-django-master/user_profile_with_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

urlpatterns += staticfiles_urlpatterns()

handler404 = 'user_profile_with_django.views.custom_page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_User_Authentication/user-profile-with-django-master/templates/home.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block body %}
    <div class="grid-25">
        <a href="https://github.com/vabhatt/user-profile-with-django" target="_blank"><img class="github-logo"
                                                                                            src="{% static 'images/GitHub-Mark.png' %}"></a>
        <p>The source code for this project is hosted on <a href="https://github.com/vabhatt/user-profile-with-django"
                                                            target="_blank">GitHub</a>.
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        <p>This is a sample Django user login project. Features include:</p>
        <ul>
            <li>Custom password validation</li>
            <li>A password strength “meter” that displays when validating passwords</li>
            <li>Ability for user to change existing password</li>
            <li>User profile page with various editable fields that contain custom validation as needed</li>
            <li>JavaScript date dropdown for the Date of Birth validation feature</li>
            <li>Basic HTML stripping for text formatting on the "bio" text area</li>
            <li>Online image editor for the user avatar. Includes basic functionality: rotate, crop and flip</li>
        </ul>
    </div>
{% endblock %}

Django_User_Authentication/user-profile-with-django-master/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'js/autogrow.js' %}"></script>
    {% block scripts %}{% endblock %}
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'accounts:profile' username=request.user.username %}">View Profile</a>
                            </li>
                            <li><a href="{% url 'accounts:edit_profile' username=request.user.username %}">Edit
                                Profile</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign
                                In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>