Django_User_Authentication/user-profile-with-django-master/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/change_password/<str:username>', views.change_password, name='change_password'),
    path('profile/edit/<str:username>', views.edit_profile, name='edit_profile'),
    path('profile/<str:username>', views.view_profile, name='profile'),
]

Django_User_Authentication/user-profile-with-django-master/user_profile_with_django/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

urlpatterns += staticfiles_urlpatterns()

handler404 = 'user_profile_with_django.views.custom_page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_User_Authentication/user-profile-with-django-master/accounts/models.py
from django.contrib.auth.models import User                     --->   User objects are the core of the authentication system. 
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

avatar_storage = FileSystemStorage(location='/media/avatars')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    city = models.CharField(max_length=100, blank=True)
    state = models.CharField(max_length=100, blank=True)
    fav_animal = models.CharField(max_length=100, blank=True)
    hobby = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(upload_to='avatars', default='blank-avatar.png')

    def clean(self):
        bio_length = 10

        if len(self.bio) <= bio_length:
            raise ValidationError("Bio data must be at least {} characters long.".format(bio_length))


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

Django_User_Authentication/user-profile-with-django-master/accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm

from .models import User, Profile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')


class UserForm(forms.ModelForm):
    confirm_email = forms.EmailField(max_length=254)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.initial['confirm_email'] = self.initial['email']

    def clean_confirm_email(self):
        """
        Validate that the validate_email field is the same as the email field.
        """
        first_email_field = self.cleaned_data["email"]
        second_email_field = self.cleaned_data["confirm_email"]

        if first_email_field != second_email_field:
            raise forms.ValidationError("Email fields don't match", code='invalid')
        return second_email_field

    class Meta:
        model = User
        fields = ('username', 'email', 'confirm_email', 'first_name', 'last_name')


class ProfileForm(forms.ModelForm):
    birth_date = forms.CharField(
        widget=forms.TextInput(
            attrs={'data-format': 'YYYY-MM-DD',
                   'data-template': 'D MMM YYYY',
                   'value': '1990-01-01',
                   }))

    class Meta:
        model = Profile
        fields = ('birth_date', 'bio', 'city', 'state', 'hobby', 'fav_animal', 'avatar')


class PasswordChangeCustomForm(PasswordChangeForm):
    def clean_new_password1(self):
        """
        Validate that the new_password field is not the same as the old_password field.
        """
        old_password = self.cleaned_data["old_password"]
        new_password = self.cleaned_data["new_password1"]

        if new_password == old_password:
            raise forms.ValidationError('Password cannot be the same as the previous password.', code='invalid')
        return new_password

Django_User_Authentication/user-profile-with-django-master/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import UserForm, ProfileForm, PasswordChangeCustomForm, SignUpForm
from .models import User


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    username = request.user.username
                    return HttpResponseRedirect(
                        reverse('accounts:profile', kwargs={'username': username})
                    )
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! You've been signed in, too."
            )
            username = request.user.username
            return HttpResponseRedirect(reverse('accounts:profile', kwargs={'username': username}))
    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required
def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def edit_profile(request, username):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request,
                "Great! Additions to your profile have been saved."
            )
            return HttpResponseRedirect(reverse('accounts:profile', kwargs={'username': request.user.username}))
    else:
        user = User.objects.get(username=username)
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def view_profile(request, username):
    user = User.objects.get(username=username)

    return render(request, 'accounts/profile.html', {
        'user': user,
    })


@login_required
def change_password(request, username):
    if request.method == 'POST':
        change_password_form = PasswordChangeCustomForm(request.user, request.POST)

        if change_password_form.is_valid():
            user = change_password_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated.')
            return HttpResponseRedirect(reverse('accounts:profile', kwargs={'username': request.user.username}))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        change_password_form = PasswordChangeCustomForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': change_password_form
    })

Django_User_Authentication/user-profile-with-django-master/accounts/templates/accounts/change_password.html
{% extends "layout.html" %}

{% block title %}Change Password | {{ super }}{% endblock %}

{% load static from staticfiles %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/password.js' %}"></script>
{% endblock %}

{% block body %}
    <h1>Update Password</h1>
    <form method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="fieldWrapper">
            {{ form.old_password.errors }}
            <label for="{{ form.old_password.id_for_label }}">Old password:</label>
            {{ form.old_password }}
        </div>
        <div class="fieldWrapper form-group">
            {{ form.new_password1.errors }}
            <label for="{{ form.new_password1.id_for_label }}">New password:</label>
            {{ form.new_password1 }}
        </div>
        <div class="fieldWrapper">
            {{ form.new_password2.errors }}
            <label for="{{ form.new_password2.id_for_label }}">New password confirmation:</label>
            {{ form.new_password2 }}
        </div>
        <button type="submit">Save changes</button>
    </form>
{% endblock %}

Django_User_Authentication/user-profile-with-django-master/accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}

{% block title %}Edit Profile | {{ super }}{% endblock %}

{% load static from staticfiles %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/combodate.min.js' %}"></script>
{% endblock %}

{% block body %}
<h1>Edit {{ user.username.title }}'s Profile</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Save changes</button>
</form>
<p><a href="{% url 'accounts:change_password' username=request.user.username %}">Change password</a></p>
{% endblock %}

Django_User_Authentication/user-profile-with-django-master/accounts/templates/accounts/profile.html
{% extends 'layout.html' %}
{% load imagekit %}

{% block body %}
    <div class="grid-50">
        <h1>{{ user.username.title }}'s Profile</h1>
        <p>Email: {{ user.email }}</p>
        <p>First Name: {{ user.first_name }}</p>
        <p>Last Name: {{ user.last_name }}</p>
        <p>Birthday: {{ user.profile.birth_date }}</p>
        <p>Bio: {{ user.profile.bio }}</p>
        <p>City: {{ user.profile.city }}</p>
        <p>State: {{ user.profile.state }}</p>
        <p>Favorite Animal: {{ user.profile.fav_animal }}</p>
        <p>Hobby: {{ user.profile.hobby }}</p>
    </div>
    <div class="grid-50 profile-img">
    {% generateimage 'accounts:profile_pic' source=user.profile.avatar %}
    </div>
{% endblock %}

Django_User_Authentication/user-profile-with-django-master/accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

Django_User_Authentication/user-profile-with-django-master/accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% load static from staticfiles %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/password.js' %}"></script>
{% endblock %}

{% block body %}
    <form method="POST" action="{% url 'accounts:sign_up' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <div class="fieldWrapper">
            {{ form.first_name.errors }}
            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.first_name }}
        </div>
        <div class="fieldWrapper">
            {{ form.last_name.errors }}
            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.last_name }}
        </div>
        <div class="fieldWrapper">
            {{ form.username.errors }}
            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}
        </div>
        <div class="fieldWrapper form-group">
            {{ form.password1.errors }}
            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }}
        </div>
        <div class="fieldWrapper">
            {{ form.password2.errors }}
            <label for="{{ form.password2.id_for_label }}">Password confirmation:</label>
            {{ form.password2 }}
        </div>
        <input type="submit" class="button-primary" value="Sign Up"></form>
{% endblock %}